-- ==============================================================================
-- MIGRASI SUPABASE: Fix & Lengkapi Kolom Tabel Sembako (Broker Distributor)
-- Salin dan jalankan script SQL ini di Supabase Dashboard -> SQL Editor
-- ==============================================================================

-- 1. TABEL: sembako_stock_batches
ALTER TABLE IF EXISTS sembako_stock_batches
  ADD COLUMN IF NOT EXISTS batch_code TEXT,
  ADD COLUMN IF NOT EXISTS qty_masuk NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS qty_sisa NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS buy_price NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS purchase_date DATE DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS expiry_date DATE,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

-- 2. TABEL: sembako_products
ALTER TABLE IF EXISTS sembako_products
  ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'lainnya',
  ADD COLUMN IF NOT EXISTS unit TEXT DEFAULT 'pcs',
  ADD COLUMN IF NOT EXISTS current_stock NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS avg_buy_price NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sell_price NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS min_stock_alert NUMERIC DEFAULT 10,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

-- 3. TABEL: sembako_sales
ALTER TABLE IF EXISTS sembako_sales
  ADD COLUMN IF NOT EXISTS customer_id UUID,
  ADD COLUMN IF NOT EXISTS customer_name TEXT,
  ADD COLUMN IF NOT EXISTS invoice_number TEXT,
  ADD COLUMN IF NOT EXISTS transaction_date DATE DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS due_date DATE,
  ADD COLUMN IF NOT EXISTS total_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_cogs NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS delivery_cost NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS other_cost NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'belum_lunas',
  ADD COLUMN IF NOT EXISTS paid_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

-- 4. TABEL: sembako_sale_items
ALTER TABLE IF EXISTS sembako_sale_items
  ADD COLUMN IF NOT EXISTS product_id UUID,
  ADD COLUMN IF NOT EXISTS product_name TEXT,
  ADD COLUMN IF NOT EXISTS unit TEXT,
  ADD COLUMN IF NOT EXISTS quantity NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS price_per_unit NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cogs_per_unit NUMERIC DEFAULT 0;

-- 5. TABEL: sembako_stock_out
ALTER TABLE IF EXISTS sembako_stock_out
  ADD COLUMN IF NOT EXISTS product_id UUID,
  ADD COLUMN IF NOT EXISTS batch_id UUID,
  ADD COLUMN IF NOT EXISTS sale_id UUID,
  ADD COLUMN IF NOT EXISTS qty_keluar NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS buy_price NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reason TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

-- 6. TABEL: sembako_customers
ALTER TABLE IF EXISTS sembako_customers
  ADD COLUMN IF NOT EXISTS customer_name TEXT,
  ADD COLUMN IF NOT EXISTS customer_type TEXT DEFAULT 'warung',
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS area TEXT,
  ADD COLUMN IF NOT EXISTS payment_terms TEXT DEFAULT 'cash',
  ADD COLUMN IF NOT EXISTS credit_limit NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reliability_score NUMERIC DEFAULT 100,
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

-- 7. TABEL: sembako_suppliers
ALTER TABLE IF EXISTS sembako_suppliers
  ADD COLUMN IF NOT EXISTS supplier_name TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

-- 8. TABEL: sembako_returns
ALTER TABLE IF EXISTS sembako_returns
  ADD COLUMN IF NOT EXISTS product_id UUID,
  ADD COLUMN IF NOT EXISTS return_type TEXT DEFAULT 'sale_return',
  ADD COLUMN IF NOT EXISTS customer_id UUID,
  ADD COLUMN IF NOT EXISTS supplier_id UUID,
  ADD COLUMN IF NOT EXISTS quantity NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS unit_price NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reason TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

-- 9. TABEL: sembako_deliveries
ALTER TABLE IF EXISTS sembako_deliveries
  ADD COLUMN IF NOT EXISTS sale_id UUID,
  ADD COLUMN IF NOT EXISTS employee_id UUID,
  ADD COLUMN IF NOT EXISTS driver_name TEXT,
  ADD COLUMN IF NOT EXISTS vehicle_type TEXT,
  ADD COLUMN IF NOT EXISTS vehicle_plate TEXT,
  ADD COLUMN IF NOT EXISTS delivery_date DATE DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS delivery_area TEXT,
  ADD COLUMN IF NOT EXISTS delivery_cost NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

-- 10. REFRESH SUPABASE SCHEMA CACHE (PGRST204 SOLVER)
NOTIFY pgrst, 'reload schema';
